import Head from "next/head";
import { SignInButton, UserButton, useUser } from "@clerk/nextjs";
import { api } from "~/utils/api";

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const { user } = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-slate-200 p-4 text-black">
        {user ? (
          <div>
            <UserButton />
            <div>Hello, {user.firstName}</div>
          </div>
        ) : (
          <SignInButton />
        )}
      </main>
    </>
  );
}
