import Head from "next/head";
import { SignInButton, UserButton, useUser } from "@clerk/nextjs";
import { type RouterOutputs, api } from "~/utils/api";
import Image from "next/image";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";

dayjs.extend(relativeTime);

export default function Home() {
  const { data } = api.posts.getAll.useQuery();

  const { user } = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-slate-200 p-4 text-black">
        {user ? (
          <div className="flex items-center justify-end gap-x-6 ">
            <div>Hello, {user.firstName}</div>
            <UserButton />
          </div>
        ) : (
          <SignInButton />
        )}

        <div className="mx-auto max-w-5xl px-10">
          <PostWizard />
          <ul className="my-10 grid md:grid-cols-2 lg:grid-cols-3">
            {!!data?.length &&
              data.map(({ post, author }) => (
                <PostView key={post.id} post={post} author={author} />
              ))}
          </ul>
        </div>
      </main>
    </>
  );
}

type PostWithAuthor = RouterOutputs["posts"]["getAll"][number];

const PostView = ({ post, author }: PostWithAuthor) => {
  return (
    <li className="flex items-start gap-x-4">
      <Image
        placeholder="blur"
        blurDataURL={author?.profilePicture || ""}
        src={author?.profilePicture || ""}
        className="h-10 w-10"
        alt="Profile image"
        width={40}
        height={40}
      />
      <div className="flex flex-col gap-2">
        <h3 className="text-xs">
          @{author.username} | {dayjs(post.createdAt).fromNow()}
        </h3>
        {post.content}
      </div>
    </li>
  );
};

const PostWizard = () => {
  const { user } = useUser();
  console.log("user", user);

  if (!user) {
    return <div>Sign in to create a post</div>;
  }

  return (
    <div>
      <div>Post Wizard</div>
      <div className="flex ">
        <Image
          src={user.profileImageUrl}
          className="h-20 w-20"
          alt="Profile image"
          width={80}
          height={80}
        />
        <textarea
          placeholder="What's on your mind?"
          className="w-full p-2 "
        ></textarea>
      </div>
    </div>
  );
};
