import Head from "next/head";

export default function SinglePost() {
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-slate-200 p-4 text-black">
        Post view
      </main>
    </>
  );
}
